/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-high": "#ece8e1",
        "surface": "#fdf9f2",
        "secondary": "#795741",
        "error": "#ba1a1a",
        "on-primary-container": "#bb9c8f",
        "secondary-container": "#ffd1b5",
        "surface-container-highest": "#e6e2db",
        "outline": "#81746f",
        "on-tertiary-fixed-variant": "#58432e",
        "surface-bright": "#fdf9f2",
        "inverse-on-surface": "#f4f0e9",
        "surface-dim": "#dddad3",
        "tertiary": "#31200e",
        "on-tertiary": "#ffffff",
        "on-primary-fixed": "#29170f",
        "error-container": "#ffdad6",
        "primary-fixed-dim": "#e1c0b1",
        "tertiary-container": "#493522",
        "secondary-fixed-dim": "#eabda2",
        "inverse-surface": "#31302c",
        "on-secondary": "#ffffff",
        "secondary-fixed": "#ffdbc7",
        "tertiary-fixed-dim": "#e0c1a6",
        "on-primary": "#ffffff",
        "outline-variant": "#d3c3bd",
        "background": "#fdf9f2",
        "on-background": "#1c1c18",
        "surface-variant": "#e6e2db",
        "on-secondary-fixed": "#2d1505",
        "surface-container": "#f1ede6",
        "on-primary-fixed-variant": "#594137",
        "primary-fixed": "#fedbcd",
        "on-secondary-fixed-variant": "#5f402b",
        "surface-container-low": "#f7f3ec",
        "surface-tint": "#72594d",
        "on-surface-variant": "#4f4440",
        "primary": "#321f16",
        "inverse-primary": "#e1c0b1",
        "on-error-container": "#93000a",
        "on-tertiary-fixed": "#281807",
        "tertiary-fixed": "#fdddc1",
        "on-error": "#ffffff",
        "on-tertiary-container": "#ba9d84",
        "primary-container": "#4a342a",
        "on-secondary-container": "#7a5742",
        "on-surface": "#1c1c18",
        "surface-container-lowest": "#ffffff",
        "linen": "#F7F3EC",
        "khaki": "#7D5A44",
        "camel": "#9C6B48",
        "cocoa": "#7D5A44",
        "espresso": "#2A1810",
      },
      borderRadius: {
        "DEFAULT": "1rem",
        "lg": "2rem",
        "xl": "3rem",
        "full": "9999px",
      },
      fontFamily: {
        "display-lg": ["Space Grotesk", "sans-serif"],
        "headline-lg": ["Space Grotesk", "sans-serif"],
        "headline-md": ["Space Grotesk", "sans-serif"],
        "headline-sm": ["Space Grotesk", "sans-serif"],
        "body-lg": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Plus Jakarta Sans", "sans-serif"],
        "body-sm": ["Plus Jakarta Sans", "sans-serif"],
        "label-lg": ["Plus Jakarta Sans", "sans-serif"],
        "label-md": ["JetBrains Mono", "monospace"],
        "label-sm": ["JetBrains Mono", "monospace"],
        "mono": ["JetBrains Mono", "monospace"],
      },
    },
  },
  plugins: [],
};
